export const products = [
  {
    title: "%100 Pamuk Oxford Slim Fit Dar Kesim Düğmeli Yaka Beyaz...",
    price: 3333.99,
    image: "/suit/card1/product (1).jpeg",
    image1: "/suit/card1/product (3).jpeg",
    image2: "/suit/card1/product (5).jpeg",
    image3: "/suit/card1/product (4).jpeg",
    image4: "/suit/card1/product (7).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 1,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Lacivert Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/card2/product(1).jpeg",
    image1: "/suit/card2/product(2).jpeg",
    image2: "/suit/card2/product(3).jpeg",
    image3: "/suit/card2/product(4).jpeg",
    image4: "/suit/card2/product(5).jpeg",
    image5: "/suit/card2/product(6).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 2,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/card3/product (1).jpeg",
    image1: "/suit/card3/product (2).jpeg",
    image2: "/suit/card3/product (3).jpeg",
    image3: "/suit/card3/product (4).jpeg",
    image4: "/suit/card3/product (5).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 3,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Desenli Gri Yelekli Takm Elbise",
    price: 6719.32,
    oldPrice: null,
    image: "/suit/card4/product(1).jpeg",
    image1: "/suit/card4/product(2).jpeg",
    image2: "/suit/card4/product(3).jpeg",  
    image3: "/suit/card4/product(4).jpeg",
    image4: "/suit/card4/product(5).jpeg",
    image5: "/suit/card4/product(6).jpeg",
    image6: "/suit/card4/product(7).jpeg",
    image7: "/suit/card4/product(8).jpeg",
    image8: "/suit/card4/product(9).jpeg",
    image9: "/suit/card4/product(10).jpeg",
    createdAt: "2023-08-01",
    salesCount: 250,
    ratingCount: 30,
    id: 4,
  },
  {
    title:
      "Su Geçirmez Slim Fit Dar Kesim Mono Yaka ünlü Yelekli Nano Siyah Yelekli Takım Elbise",
    price: 5743.5,
    oldPrice: null,
    image: "/suit/card5/product(1).jpeg",
    image1: "/suit/card5/product(2).jpeg",
    image2: "/suit/card5/product(3).jpeg",
    image3: "/suit/card5/product(4).jpeg",
    image4: "/suit/card5/product(5).jpeg",
    image5: "/suit/card5/product(6).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 5,
  },
  {
    title: "Ekstra Slim Fit Dar Kesim Kirlangıç Yaka Siyah Takım Elbise",
    price: 4516.67,
    oldPrice: null,
    image: "/suit/card6/product(1).jpeg",
    image1: "/suit/card6/product(2).jpeg",
    image2: "/suit/card6/product(3).jpeg",
    image3: "/suit/card6/product(4).jpeg",
    image4: "/suit/card6/product(5).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 6,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Lacivert Takm Elbise",
    price: 3333.99,
    oldPrice: 453.99,
    image: "/suit/card7/ (1).jpeg",
    image1: "/suit/card7/ (2).jpeg",
    image2: "/suit/card7/ (3).jpeg",
    image3: "/suit/card7/ (4).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 18,
  }
];
