export const trousersproducts = [
  {
    title: "Slim Fit Dar Kesim Beli Baélamall Yan Cep Gofrel Desenli Lacivert Pantolon",
    price: 3353.99,
    image: "/trousers/card1/photo (1).jpeg",
    image1: "/trousers/card1/photo (2).jpeg",
    image2: "/trousers/card1/photo (3).jpeg",
    image3: "/trousers/card1/photo (4).jpeg",
    createdAt: "2023-06-10",
    salesCount: 250,
    ratingCount: 150,
    id: 51,
    oldPrice: 500,
  },
  {
    title: "Slim Fit Dar Kesim 5 Cep Pamuklu Esnek Hakim Chino Pantolon",
    price: 1333.99,
    oldPrice: null,
    image: "/trousers/card2/photo (1).jpeg",
    image1: "/trousers/card2/photo (2).jpeg",
    image2: "/trousers/card2/photo (3).jpeg",
    image3: "/trousers/card2/photo (5).jpeg",
    image4: "/trousers/card2/photo (4).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 62,
  },
  {
    title: "Slim Fit Dar Kesim 5 Cep Pamuklu Esnek Siyah Chino Pantolon",
    price: 5333.99,
    oldPrice: null,
    image: "/trousers/card3/photo (1).jpeg",
    image1: "/trousers/card3/photo (2).jpeg",
    image2: "/trousers/card3/photo (3).jpeg",
    image3: "/trousers/card3/photo (4).jpeg",
    image4: "/trousers/card3/photo (5).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 63,
  },
  {
    title: "Slim Fit Dar Kesim Yan Cep Pamuklu Esnek Siyah Chino Pantolon",
    price: 6719.32,
    oldPrice: null,
    image: "/trousers/card4/photo (1).jpeg",
    image1: "/trousers/card4/photo (2).jpeg",
    image2: "/trousers/card4/photo (3).jpeg",  
    image3: "/trousers/card4/photo (4).jpeg",
    createdAt: "2023-08-01",
    salesCount: 250,
    ratingCount: 30,
    id: 64,
  },
  {
    title:
      "Slim Fit Dar Kesim Yan Cep Pamuklu Esnek Haki Chino Pantolon",
    price: 5743.5,
    oldPrice: null,
    image: "/trousers/card5/photo (1).jpeg",
    image1: "/trousers/card5/photo (2).jpeg",
    image2: "/trousers/card5/photo (3).jpeg",
    image3: "/trousers/card5/photo (4).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 65,
  },
];
