export const products = [
  {
    title: "%100 Pamuk Oxford Slim Fit Dar Kesim Düğmeli Yaka Beyaz...",
    price: 3333.99,
    image: "/suit/product (1).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 1,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Lacivert Takm Elbise",
    price: 3333.99,
    oldPrice: 453.99,
    image: "/suit/product (2).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 2,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/product (3).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 3,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Desenli Gri Yelekli Takm Elbise",
    price: 6719.32,
    oldPrice: 679.99,
    image: "/suit/product (4).jpeg",
    createdAt: "2023-08-01",
    salesCount: 250,
    ratingCount: 30,
    id: 4,
  },
  {
    title:
      "Su Geçirmez Slim Fit Dar Kesim Mono Yaka ünlü Yelekli Nano Siyah Yelekli Takım Elbise",
    price: 5743.5,
    oldPrice: 773.99,
    image: "/suit/product (5).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 5,
  },
  {
    title: "Ekstra Slim Fit Dar Kesim Kirlangıç Yaka Siyah Takım Elbise",
    price: 4516.67,
    oldPrice: 453.99,
    image: "/suit/product (6).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 6,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Lacivert Takm Elbise",
    price: 3333.99,
    oldPrice: 453.99,
    image: "/suit/product (7).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 7,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/product (8).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 8,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/product (9).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 9,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/product (10).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 10,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/product (11).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 11,
  },
  {
    title: "%100 Pamuk Oxford Slim Fit Dar Kesim Düğmeli Yaka Beyaz...",
    price: 3333.99,
    image: "/suit/product (1).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 12,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Lacivert Takm Elbise",
    price: 3333.99,
    oldPrice: 453.99,
    image: "/suit/product (2).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 13,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/product (3).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 14,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Desenli Gri Yelekli Takm Elbise",
    price: 6719.32,
    oldPrice: 679.99,
    image: "/suit/product (4).jpeg",
    createdAt: "2023-08-01",
    salesCount: 250,
    ratingCount: 30,
    id: 15,
  },
  {
    title:
      "Su Geçirmez Slim Fit Dar Kesim Mono Yaka ünlü Yelekli Nano Siyah Yelekli Takım Elbise",
    price: 5743.5,
    oldPrice: 773.99,
    image: "/suit/product (5).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 16,
  },
  {
    title: "Ekstra Slim Fit Dar Kesim Kirlangıç Yaka Siyah Takım Elbise",
    price: 4516.67,
    oldPrice: 453.99,
    image: "/suit/product (6).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 17,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Lacivert Takm Elbise",
    price: 3333.99,
    oldPrice: 453.99,
    image: "/suit/product (7).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 18,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/product (8).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 19,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/product (9).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 20,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/product (10).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 21,
  },
  {
    title: "Slim Fit Dar Kesim Mono Yaka Siyah Takm Elbise",
    price: 3333.99,
    oldPrice: null,
    image: "/suit/product (11).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 22,
  },
];
