export const shirts = [
  {
    title: "%IOO Pamuk Flamll Oxford Slim Fit Dar Kesim Dugmeli Yaka Beyaz Gömlek",
    price: 3333.99,
    image: "/shirt/card1/photo (1).jpeg",
    image1: "/shirt/card1/photo (2).jpeg",
    image2: "/shirt/card1/photo (3).jpeg",
    image3: "/shirt/card1/photo (4).jpeg",
    image4: "/suit/card1/photo (5).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 1,
  },
  {
    title: "Kolay Utülenebilir Slim Fit Dar Kesim Klasik Yaka Pamuklu Beyaz Gömlek",
    price: 3333.99,
    oldPrice: 3.9999,
    image: "/shirt/card2/photo (1).jpeg",
    image1: "/shirt/card2/photo (2).jpeg",
    image2: "/shirt/card2/photo (3).jpeg",
    image3: "/shirt/card2/photo (4).jpeg",
    image4: "/shirt/card2/photo (5).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 2,
  },
  {
    title: "Dü5meIi Yaka Kolay Utülenebilir Pamuklu Slim Fit Dar Kesim Oxford Gri Gömlek",
    price: 3333.99,
    oldPrice: null,
    image: "/shirt/card3/photo (1).jpeg",
    image1: "/shirt/card3/photo (2).jpeg",
    image2: "/shirt/card3/photo (3).jpeg",
    image3: "/shirt/card3/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 3,
  },
  {
    title: "%IOO Pamuk Flamll Oxford Slim Fit Dar Kesim Dugmeli Yaka Beyaz Gömlek",
    price: 3333.99,
    image: "/shirt/card1/photo (1).jpeg",
    image1: "/shirt/card1/photo (2).jpeg",
    image2: "/shirt/card1/photo (3).jpeg",
    image3: "/shirt/card1/photo (4).jpeg",
    image4: "/suit/card1/photo (5).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 1,
  },
  {
    title: "Kolay Utülenebilir Slim Fit Dar Kesim Klasik Yaka Pamuklu Beyaz Gömlek",
    price: 3333.99,
    oldPrice: 3.9999,
    image: "/shirt/card2/photo (1).jpeg",
    image1: "/shirt/card2/photo (2).jpeg",
    image2: "/shirt/card2/photo (3).jpeg",
    image3: "/shirt/card2/photo (4).jpeg",
    image4: "/shirt/card2/photo (5).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 2,
  },
  {
    title: "Dü5meIi Yaka Kolay Utülenebilir Pamuklu Slim Fit Dar Kesim Oxford Gri Gömlek",
    price: 3333.99,
    oldPrice: null,
    image: "/shirt/card3/photo (1).jpeg",
    image1: "/shirt/card3/photo (2).jpeg",
    image2: "/shirt/card3/photo (3).jpeg",
    image3: "/shirt/card3/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 3,
  },
  {
    title: "%IOO Pamuk Flamll Oxford Slim Fit Dar Kesim Dugmeli Yaka Beyaz Gömlek",
    price: 3333.99,
    image: "/shirt/card1/photo (1).jpeg",
    image1: "/shirt/card1/photo (2).jpeg",
    image2: "/shirt/card1/photo (3).jpeg",
    image3: "/shirt/card1/photo (4).jpeg",
    image4: "/suit/card1/photo (5).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 1,
  },
  {
    title: "Kolay Utülenebilir Slim Fit Dar Kesim Klasik Yaka Pamuklu Beyaz Gömlek",
    price: 3333.99,
    oldPrice: 3.9999,
    image: "/shirt/card2/photo (1).jpeg",
    image1: "/shirt/card2/photo (2).jpeg",
    image2: "/shirt/card2/photo (3).jpeg",
    image3: "/shirt/card2/photo (4).jpeg",
    image4: "/shirt/card2/photo (5).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 2,
  },
  {
    title: "Dü5meIi Yaka Kolay Utülenebilir Pamuklu Slim Fit Dar Kesim Oxford Gri Gömlek",
    price: 3333.99,
    oldPrice: null,
    image: "/shirt/card3/photo (1).jpeg",
    image1: "/shirt/card3/photo (2).jpeg",
    image2: "/shirt/card3/photo (3).jpeg",
    image3: "/shirt/card3/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 3,
  },
  {
    title: "%IOO Pamuk Flamll Oxford Slim Fit Dar Kesim Dugmeli Yaka Beyaz Gömlek",
    price: 3333.99,
    image: "/shirt/card1/photo (1).jpeg",
    image1: "/shirt/card1/photo (2).jpeg",
    image2: "/shirt/card1/photo (3).jpeg",
    image3: "/shirt/card1/photo (4).jpeg",
    image4: "/suit/card1/photo (5).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 1,
  },
  {
    title: "Kolay Utülenebilir Slim Fit Dar Kesim Klasik Yaka Pamuklu Beyaz Gömlek",
    price: 3333.99,
    oldPrice: 3.9999,
    image: "/shirt/card2/photo (1).jpeg",
    image1: "/shirt/card2/photo (2).jpeg",
    image2: "/shirt/card2/photo (3).jpeg",
    image3: "/shirt/card2/photo (4).jpeg",
    image4: "/shirt/card2/photo (5).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 2,
  },
  {
    title: "Dü5meIi Yaka Kolay Utülenebilir Pamuklu Slim Fit Dar Kesim Oxford Gri Gömlek",
    price: 3333.99,
    oldPrice: null,
    image: "/shirt/card3/photo (1).jpeg",
    image1: "/shirt/card3/photo (2).jpeg",
    image2: "/shirt/card3/photo (3).jpeg",
    image3: "/shirt/card3/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 3,
  },
  {
    title: "%IOO Pamuk Flamll Oxford Slim Fit Dar Kesim Dugmeli Yaka Beyaz Gömlek",
    price: 3333.99,
    image: "/shirt/card1/photo (1).jpeg",
    image1: "/shirt/card1/photo (2).jpeg",
    image2: "/shirt/card1/photo (3).jpeg",
    image3: "/shirt/card1/photo (4).jpeg",
    image4: "/suit/card1/photo (5).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 1,
  },
  {
    title: "Kolay Utülenebilir Slim Fit Dar Kesim Klasik Yaka Pamuklu Beyaz Gömlek",
    price: 3333.99,
    oldPrice: 3.9999,
    image: "/shirt/card2/photo (1).jpeg",
    image1: "/shirt/card2/photo (2).jpeg",
    image2: "/shirt/card2/photo (3).jpeg",
    image3: "/shirt/card2/photo (4).jpeg",
    image4: "/shirt/card2/photo (5).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 2,
  },
  {
    title: "Dü5meIi Yaka Kolay Utülenebilir Pamuklu Slim Fit Dar Kesim Oxford Gri Gömlek",
    price: 3333.99,
    oldPrice: null,
    image: "/shirt/card3/photo (1).jpeg",
    image1: "/shirt/card3/photo (2).jpeg",
    image2: "/shirt/card3/photo (3).jpeg",
    image3: "/shirt/card3/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 3,
  },
  
  
  
];
