export const productsshirts = [
  {
    title: "%IOO Pamuk Flamll Oxford Slim Fit Dar Kesim Dugmeli Yaka Beyaz Gömlek",
    price: 533.99,
    image: "/shirt/card1/photo (1).jpeg",
    image1: "/shirt/card1/photo (2).jpeg",
    image2: "/shirt/card1/photo (3).jpeg",
    image3: "/shirt/card1/photo (4).jpeg",
    image4: "/suit/card1/photo (5).jpeg",
    createdAt: "2023-06-10",
    salesCount: 150,
    ratingCount: 20,
    id: 11,
  },
  {
    title: "Kolay Utülenebilir Slim Fit Dar Kesim Klasik Yaka Pamuklu Beyaz Gömlek",
    price: 833.99,
    oldPrice: 3.9999,
    image: "/shirt/card2/photo (1).jpeg",
    image1: "/shirt/card2/photo (2).jpeg",
    image2: "/shirt/card2/photo (3).jpeg",
    image3: "/shirt/card2/photo (4).jpeg",
    image4: "/shirt/card2/photo (5).jpeg",
    createdAt: "2023-07-12",
    salesCount: 300,
    ratingCount: 45,
    id: 12,
  },
  {
    title: "Düğmeli Yaka Kolay Utülenebilir Pamuklu Slim Fit Dar Kesim Oxford Gri Gömlek",
    price: 633.99,
    oldPrice: null,
    image: "/shirt/card3/photo (1).jpeg",
    image1: "/shirt/card3/photo (2).jpeg",
    image2: "/shirt/card3/photo (3).jpeg",
    image3: "/shirt/card3/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 13,
  },   
  {
    title: "Düğmeli Yaka Kolay Utülenebilir Pamuklu Slim Fit Dar Kesim Oxford Beyaz Gömlek",
    price: 335,
    oldPrice: null,
    image: "/shirt/card4/photo (1).jpeg",
    image1: "/shirt/card4/photo (2).jpeg",
    image2: "/shirt/card4/photo (3).jpeg",
    image3: "/shirt/card4/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 10,
    id: 14,
  },
  {
    title: "%100 Pamuk Flanel Oxford Slim Fit Dar Kesim Düğmeli Yaka Bej Gömlek",
    price: 569,
    oldPrice: null,
    image: "/shirt/card5/photo (1).jpeg",
    image1: "/shirt/card5/photo (2).jpeg",
    image2: "/shirt/card5/photo (3).jpeg",
    image3: "/shirt/card5/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 35,
    id: 15,
  },
  {
    title: "Kolay Utülenebilir Non-Iron Pamuklu Comfort Fit Geniş Kesim Klasik Yaka Siyah Gömlek",
    price: 675,
    oldPrice: null,
    image: "/shirt/card6/photo (1).jpeg",
    image1: "/shirt/card6/photo (2).jpeg",
    image2: "/shirt/card6/photo (3).jpeg",
    image3: "/shirt/card6/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 50,
    id: 16,
  },
  {
    title: "Slim Fit Dar Kesim Düğmeli Yaka Desenli Beyaz Gömlek",
    price: 965,
    oldPrice: null,
    image: "/shirt/card7/photo (1).jpeg",
    image1: "/shirt/card7/photo (2).jpeg",
    image2: "/shirt/card7/photo (3).jpeg",
    image3: "/shirt/card7/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 50,
    id: 17,
  },
  {
    title: "Slim Fit Dar Kesim 0/0100 Pamuk Düğmeli Yaka Oxford Yeşil Gömlek",
    price: 1000,
    oldPrice: null,
    image: "/shirt/card8/photo (1).jpeg",
    image1: "/shirt/card8/photo (2).jpeg",
    image2: "/shirt/card8/photo (3).jpeg",
    image3: "/shirt/card8/photo (4).jpeg",
    createdAt: "2023-05-05",
    salesCount: 75,
    ratingCount: 50,
    id: 18,
  },
  
];
