export const productpolo = [
 
  {
    title: "Slim Fit Dar Kesim Kivrllmaz Polo Yaka Kisa Kollu Sihah Tişört",
    price: 533.99,
    image: "/polotshirt/card1/photo (1).jpeg",
    image1: "/polotshirt/card1/photo (2).jpeg",
    image2: "/polotshirt/card1/photo (3).jpeg",
    image3: "/polotshirt/card1/photo (4).jpeg",
    createdAt: "2023-06-10",
    oldPrice: 599.99,
    salesCount: 150,
    ratingCount: 20,
    id: 31,
  },
  {
    title: "Basic Tişört",
    price: 499.99,
    image: "/polotshirt/card2/photo (1).jpeg",
    image1: "/polotshirt/card2/photo (2).jpeg",
    image2: "/polotshirt/card2/photo (3).jpeg",
    image3: "/polotshirt/card2/photo (4).jpeg",
    createdAt: "2023-06-15",
    oldPrice: 549.99,
    salesCount: 200,
    ratingCount: 30,
    id: 32,
  },
  {
    title: "Basic Tişört",
    price: 499.99,
    image: "/polotshirt/card3/photo (1).jpeg",
    image1: "/polotshirt/card3/photo (2).jpeg",
    image2: "/polotshirt/card3/photo (3).jpeg",
    image3: "/polotshirt/card3/photo (4).jpeg",
    createdAt: "2023-06-20",
    oldPrice: 649.99,
    salesCount: 250,
    ratingCount: 40,
    id: 33,
  },
  {
    title: "Basic Tişört",
    price: 499.99,
    image: "/polotshirt/card4/photo (1).jpeg",
    image1: "/polotshirt/card4/photo (2).jpeg",
    image2: "/polotshirt/card4/photo (3).jpeg",
    image3: "/polotshirt/card4/photo (4).jpeg",
    createdAt: "2023-06-25",
    oldPrice: 449.99,
    salesCount: 300,
    ratingCount: 50,
    id: 34,
  },
];
